const fieldOfActivity = [
    "An toàn lao động", "Biên / Phiên dịch", "Bán hàng kỹ thuật", "Bán lẻ / bán sỉ",
    "Báo chí / Truyền thông", "Bưu chính / Viễn thông", "Bảo hiểm", "Bảo trì / Sửa chữa",
    "Bất động sản", "Chứng khoán / Vàng / Ngoại tệ", "Công nghệ cao", "Công nghệ thông tin",
    "Công nghệ Ô tô", "Cơ khí / Chế tạo / Tự động hóa", "Du lịch", "Dược phẩm / Công nghệ sinh học",
    "Dầu khí / Hóa chất", "Dệt may / Da giày", "Dịch vụ khách hàng", "Giáo dục / Đào tạo", "Hóa học / Sinh học",
    "Hoạch định / Dự án", "Hàng cao cấp", "Hàng gia dụng", "Hàng hải", "Hàng không", "Hàng tiêu dùng",
    "Hành chính / Văn phòng", "IT phần cứng / Mạng", "IT phần mềm", "In ấn / Xuất bản", "Khách sạn / Nhà hàng",
    "Kinh doanh / Bán hàng", "Kiến trúc", "Kế toán / Kiểm toán", "Logistics", "Luật / Pháp lý",
    "Marketing / Truyền thông / Quảng cáo", "Môi trường / Xử lý chất thải", "Mỹ phẩm / Trang sức",
    "Mỹ thuật / Nghệ thuật / Điện ảnh", "NGO / Phi chính phủ / Phi lợi nhuận", "Ngân hàng / Tài chính",
    "Nhân sự", "Nông / Lâm / Ngư nghiệp", "Phi chính phủ / Phi lợi nhuận", "QA / QC", "Quản lý điều hành",
    "Spa / Làm đẹp", "Sản phẩm công nghiệp", "Sản xuất", "Thiết kế nội thất", "Thiết kế đồ họa", "Thư ký / Trợ lý",
    "Thời trang", "Thực phẩm / Đồ uống", "Tài chính / Đầu tư", "Tư vấn", "Tổ chức sự kiện / Quà tặng", "Vận tải / Kho vận",
    "Xuất nhập khẩu", "Xây dựng", "Y tế / Dược", "Điện / Điện tử / Điện lạnh", "Điện tử viễn thông", "Địa chất / Khoáng sản"
]

const jobType = ["Toàn thời gian", "Bán thời gian", "Làm từ xa"];
const levelRequirement = ["Thực tập sinh", "Nhân viên", "Trưởng phòng"];
const experience = ["Không yêu cầu kinh nghiệm", "Dưới 1 năm", "1 năm", "2 năm", "3 năm", "4 năm", "5 năm", "Trên 5 năm"];
const resumeExperience = ["Chưa có kinh nghiệm", "Dưới 1 năm", "1 năm", "2 năm", "3 năm", "4 năm", "5 năm", "Trên 5 năm"];
const genderRequirement = ["Không yêu cầu", "Nam", "Nữ"];
const acceptanceStatus = ["waiting", "accept", "decline"];
const status = ["active", "inactive"];
const provinceOfVietNam = [
    "An Giang",
    "Bà Rịa - Vũng Tàu",
    "Bắc Giang",
    "Bắc Kạn",
    "Bạc Liêu",
    "Bắc Ninh",
    "Bến Tre",
    "Bình Định",
    "Bình Dương",
    "Bình Phước",
    "Bình Thuận",
    "Cà Mau",
    "Cần Thơ",
    "Cao Bằng",
    "Đà Nẵng",
    "Đắk Lắk",
    "Đắk Nông",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Giang",
    "Hà Nam",
    "Hà Nội",
    "Hà Tĩnh",
    "Hải Dương",
    "Hải Phòng",
    "Hậu Giang",
    "Hòa Bình",
    "Hưng Yên",
    "Khánh Hòa",
    "Kiên Giang",
    "Kon Tum",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lào Cai",
    "Long An",
    "Nam Định",
    "Nghệ An",
    "Ninh Bình",
    "Ninh Thuận",
    "Phú Thọ",
    "Phú Yên",
    "Quảng Bình",
    "Quảng Nam",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Sóc Trăng",
    "Sơn La",
    "Tây Ninh",
    "Thái Bình",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên Huế",
    "Tiền Giang",
    "TP Hồ Chí Minh",
    "Trà Vinh",
    "Tuyên Quang",
    "Vĩnh Long",
    "Vĩnh Phúc",
    "Yên Bái"
]

const educationLevel = [
    "Trên đại học",
    "Đại học",
    "Cao đẳng",
    "Trung cấp",
    "Trung học",
    "Chứng chỉ nghề"
]

const mapRolePermission = {
    "ADMIN": "001",
    "RECRUITER": "002",
    "CANDIDATE": "003"
}

const workStatus = ["Đang tìm việc", "Đã có việc", "Đang tìm nơi thực tập"];
const applicationStatus = ['Đã nộp', 'Đã nhận', 'Không nhận'];
const premiumPackage = ["1 tháng", "3 tháng", "6 tháng"];
const blogType = ['Định hướng nghề nghiệp', 'Bí kíp tìm việc', 'Chế độ lương thưởng', 'Kiến thức chuyên ngành'];

function sortObject(obj) {
    let sorted = {};
    let str = [];
    let key;
    for (key in obj) {
        if (obj.hasOwnProperty(key)) {
            str.push(encodeURIComponent(key));
        }
    }
    str.sort();
    for (key = 0; key < str.length; key++) {
        sorted[str[key]] = encodeURIComponent(obj[str[key]]).replace(/%20/g, "+");
    }
    return sorted;
}

const majors = [
    'Toán tin',
    'Toán ứng dụng',
    'Khoa học tính toán',
    'Toán học',
    'Thống kê',
    'Thú y',
    'Quản lý bệnh viện',
    'Tổ chức và quản lý y tế',
    'Y đa khoa',
    'Điều dưỡng',
    'Hóa dược',
    'Dược học',
    'Y học cổ truyền',
    'Y học dự phòng',
    'Y tế công cộng',
    'Kỹ thuật phục hồi chức năng',
    'Kỹ thuật hình ảnh y học',
    'Kỹ thuật xét nghiệm y học',
    'Kỹ thuật phục hình răng',
    'Răng - Hàm - Mặt',
    'Dinh dưỡng',
    'Hộ sinh',
    'Công nghệ da giày',
    'Công nghệ vật liệu dệt, may',
    'Công nghệ sợi, dệt',
    'Công nghệ chế biến lâm sản',
    'Công nghệ dệt, may',
    'Đảm bảo chất lượng và an toàn thực phẩm',
    'Công nghệ chế biến thuỷ sản',
    'Công nghệ sau thu hoạch',
    'Kỹ thuật thực phẩm',
    'Công nghệ thực phẩm',
    'Luật quốc tế',
    'Luật kinh tế',
    'Luật',
    'Lâm sinh',
    'Quản lý thủy sản',
    'Khai thác thủy sản',
    'Bệnh học thủy sản',
    'Nuôi trồng thủy sản',
    'Phát triển nông thôn',
    'Kinh tế nông nghiệp',
    'Kinh doanh nông nghiệp',
    'Công nghệ rau hoa quả và cảnh quan',
    'Bảo vệ thực vật',
    'Khoa học cây trồng',
    'Nông học',
    'Chăn nuôi',
    'Khoa học đất',
    'Khuyến nông',
    'Nông nghiệp',
    'Lâm học',
    'Quản lý tài nguyên rừng',
    'Lâm nghiệp đô thị',
    'Ngôn ngữ Khmer',
    'Hán Nôm',
    'Tiếng Việt và văn hoá Việt Nam',
    'Văn hoá các dân tộc thiểu số Việt Nam',
    'Sáng tác Văn học',
    'Ngôn ngữ Ả Rập',
    'Ngôn ngữ Hàn Quốc',
    'Ngôn ngữ Nhật',
    'Ngôn ngữ Bồ Đào Nha',
    'Ngôn ngữ Tây Ban Nha',
    'Ngôn ngữ Trung Quốc',
    'Ngôn ngữ Đức',
    'Ngôn ngữ Pháp',
    'Ngôn ngữ Nga',
    'Ngôn ngữ Anh',
    'Quản lý văn hóa',
    'Văn hóa học',
    'Văn học',
    'Ngôn ngữ học',
    'Lịch sử',
    'Tôn giáo học',
    'Chủ nghĩa xã hội khoa học',
    'Triết học',
    'Bảo hộ lao động',
    'Quản lý đất đai',
    'Kinh tế tài nguyên thiên nhiên',
    'Quản lý tài nguyên và môi trường',
    'Công nghệ đổi mới và sáng tạo',
    'Khoa học dữ liệu',
    'Thiết kế vi mạch',
    'Kỹ thuật máy tính',
    'Kỹ thuật phần mềm',
    'Mạng máy tính và truyền thông dữ liệu',
    'Khoa học máy tính',
    'An toàn thông tin',
    'Công nghệ thông tin',
    'Kỹ thuật tuyển khoáng',
    'Kỹ thuật dầu khí',
    'Kỹ thuật mỏ',
    'Kỹ thuật địa vật lý',
    'Kỹ thuật trắc địa - bản đồ',
    'Kỹ thuật địa chất',
    'Kỹ thuật hạt nhân',
    'Vật lý kỹ thuật',
    'Kỹ thuật môi trường',
    'Kỹ thuật vật liệu kim loại',
    'Kỹ thuật vật liệu',
    'Kỹ thuật hoá học',
    'Kỹ thuật điều khiển và tự động hóa',
    'Kỹ thuật y sinh',
    'Kỹ thuật điện tử - viễn thông',
    'Kỹ thuật điện',
    'Kỹ thuật không gian',
    'Kỹ thuật hàng không',
    'Kỹ thuật hệ thống công nghiệp',
    'Kỹ thuật công nghiệp',
    'Kỹ thuật cơ khí động lực',
    'Cơ kỹ thuật',
    'Công nghệ tài chính Fintech',
    'Công nghệ Marketing',
    'Kinh tế đối ngoại',
    'Kinh tế',
    'Hệ thống thông tin',
    'Kiểm toán',
    'Bảo hiểm',
    'Kinh doanh thương mại',
    'Khoa học quản lý',
    'Hệ thống thông tin quản lý',
    'Quản lý dự án',
    'Quan hệ lao động',
    'Quản lý công',
    'Quản trị nhân lực',
    'Quản trị văn phòng',
    'Kế toán',
    'Tài chính - Ngân hàng',
    'Kinh doanh quốc tế',
    'Marketing',
    'Bất động sản',
    'Thương mại điện tử',
    'Quản trị kinh doanh',
    'Kỹ thuật xây dựng',
    'Quản lý xây dựng',
    'Kinh tế xây dựng',
    'Quy hoạch vùng và đô thị',
    'Đô thị học',
    'Kỹ thuật cấp thoát nước',
    'Kỹ thuật tài nguyên nước',
    'Địa kỹ thuật xây dựng',
    'Kỹ thuật cơ sở hạ tầng',
    'Kỹ thuật xây dựng công trình giao thông',
    'Kỹ thuật xây dựng công trình biển',
    'Kỹ thuật xây dựng công trình thủy',
    'Thiết kế nội thất',
    'Kiến trúc cảnh quan',
    'Kiến trúc',
    'Kinh tế thể thao',
    'Kinh tế số',
    'Đông Nam Á học',
    'Quốc tế học',
    'Toán kinh tế',
    'Thống kê Kinh tế',
    'Kinh tế Chính trị',
    'Nhân học',
    'Xã hội học',
    'Tâm lý học giáo dục',
    'Tâm lý học',
    'Kinh tế quốc tế',
    'Kinh tế phát triển',
    'Kinh tế đầu tư',
    'Hàn Quốc học',
    'Nhật Bản học',
    'Việt Nam học',
    'Đông phương học',
    'Xây dựng Đảng và chính quyền nhà nước',
    'Quan hệ quốc tế',
    'Quản lý nhà nước',
    'Chính trị học',
    'Địa lý học',
    'Khoa học vật liệu',
    'Hóa học',
    'Cơ học',
    'Vật lý nguyên tử và hạt nhân',
    'Vật lý học',
    'Thiên văn học',
    'Hải dương học',
    'Thủy văn học',
    'Khí tượng và khí hậu học',
    'Địa lý tự nhiên',
    'Địa chất học',
    'Bản đồ học',
    'Khoa học môi trường',
    'Kỹ thuật sinh học',
    'Sinh học ứng dụng',
    'Công nghệ sinh học',
    'Sinh học',
    'Quản lý thể dục thể thao',
    'Quản trị nhà hàng và dịch vụ ăn uống',
    'Quản trị khách sạn',
    'Kinh tế gia đình',
    'Y sinh học thể dục thể thao',
    'Quản trị dịch vụ du lịch và lữ hành',
    'Du lịch',
    'Công tác thanh thiếu niên',
    'Công tác xã hội',
    'Khoa học hàng hải',
    'Kinh tế vận tải',
    'Quản lý hoạt động bay',
    'Khai thác vận tải',
    'Công nghệ Logistics',
    'Kỹ thuật sản xuất thông minh',
    'Robot và Trí tuệ nhân tạo',
    'Công nghệ kỹ thuật điện, điện tử',
    'Kỹ thuật in',
    'Công nghệ kỹ thuật ô tô',
    'Kỹ thuật tàu thuỷ',
    'Kỹ thuật nhiệt',
    'Kỹ thuật cơ điện tử',
    'Kỹ thuật cơ khí',
    'Công nghê kỹ thuật vật liệu xây dựng',
    'Công nghệ kỹ thuật công trình xây dựng',
    'Công nghệ kỹ thuật giao thông',
    'Công nghệ kỹ thuật kiến trúc',
    'Bảo dưỡng công nghiệp',
    'Công nghệ chế tạo máy',
    'Quản lý công nghiệp',
    'Kinh tế công nghiệp',
    'Logistics và Quản lý chuỗi cung ứng',
    'Kinh doanh xuất bản phẩm',
    'Xuất bản',
    'Bảo tàng học',
    'Lưu trữ học',
    'Quản lý thông tin',
    'Thông tin - thư viện',
    'Quan hệ công chúng',
    'Truyền thông quốc tế',
    'Công nghệ truyền thông',
    'Truyền thông đại chúng',
    'Truyền thông đa phương tiện',
    'Báo chí',
    'Quân sự cơ sở',
    'Phòng cháy chữa cháy và cứu nạn cứu hộ',
    'Quản lý nhà nước về an ninh trật tự',
    'Trinh sát cảnh sát',
    'Kỹ thuật hình sự',
    'Biên phòng',
    'Hậu cần quân sự',
    'Điều tra hình sự',
    'Trinh sát an ninh',
    'Diễn viên kịch, điện ảnh - truyền hình',
    'Diễn viên sân khấu kịch hát',
    'Công nghệ điện ảnh, truyền hình',
    'Biên kịch sân khấu',
    'Thanh nhạc',
    'Chỉ huy âm nhạc',
    'Sáng tác âm nhạc',
    'Mỹ thuật đô thị',
    'Âm nhạc học',
    'Gốm',
    'Thiết kế công nghiệp',
    'Quay phim',
    'Hội họa',
    'Biên đạo múa',
    'Thiết kế mỹ thuật sân khấu, điện ảnh',
    'Thiết kế thời trang',
    'Thiết kế đồ họa',
    'Diễn viên múa',
    'Thiết kế âm thanh, ánh sáng',
    'Nhiếp ảnh',
    'Biểu diễn nhạc cụ truyền thống',
    'Huấn luyện múa',
    'Điêu khắc',
    'Đạo diễn sân khấu',
    'Biên kịch điện ảnh, truyền hình',
    'Đạo diễn Điện ảnh - Truyền hình',
    'Lý luận, lịch sử và phê bình sân khấu',
    'Piano',
    'Biểu diễn nhạc cụ phương Tây',
    'Sư phạm Khoa học tự nhiên',
    'Quản lý giáo dục',
    'Giáo dục đặc biệt',
    'Giáo dục Thể chất',
    'Giáo dục Chính trị',
    'Giáo dục Công dân',
    'Giáo dục Tiểu học',
    'Giáo dục Mầm non',
    'Giáo dục Quốc phòng - An ninh',
    'Huấn luyện thể thao',
    'Sư phạm Công nghệ',
    'Sư phạm Tiếng Hàn Quốc',
    'Sư phạm Tiếng Nhật',
    'Sư phạm Tiếng Trung Quốc',
    'Sư phạm Tiếng Pháp',
    'Sư phạm Tiếng Anh',
    'Sư phạm Mỹ thuật',
    'Sư phạm Âm nhạc',
    'Sư phạm Tiếng Nga',
    'Sư phạm Địa lý',
    'Sư phạm Lịch sử',
    'Sư phạm Ngữ văn',
    'Sư phạm Kỹ thuật nông nghiệp',
    'Sư phạm Kỹ thuật công nghiệp',
    'Sư phạm Sinh học',
    'Sư phạm Hóa học',
    'Sư phạm Vật lý',
    'Sư phạm Tin học',
    'Sư phạm Toán học'
]


module.exports = {
    fieldOfActivity,
    jobType,
    levelRequirement,
    experience,
    educationLevel,
    genderRequirement,
    acceptanceStatus,
    status,
    provinceOfVietNam,
    mapRolePermission,
    workStatus,
    applicationStatus,
    sortObject,
    majors,
    blogType,
    premiumPackage,
    resumeExperience
}
